In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.3'

In [7]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
arr2d = np.zeros((3,2), dtype = np.int32)
arr2d.dtype

dtype('int32')

In [14]:
np.ones((3,2), dtype="f2")

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float16)

In [13]:
np.arange(5,10, dtype="f2")

array([5., 6., 7., 8., 9.], dtype=float16)

In [19]:
arr2c = np.arange(4).reshape((2,2))
arr2c

array([[0, 1],
       [2, 3]])

In [22]:
arr = np.arange(4)
np.repeat(arr,2)
np.tile(arr,2)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [24]:
arr2c.shape

(2, 2)

In [29]:
rng = np.random.default_rng(12345)
rng.integers(0,10,2*2).reshape(2,2)

array([[6, 2],
       [7, 3]])

In [36]:
arr2d = rng.integers(0,10,4*5).reshape(4,5)
np.mean(arr2d)

np.float64(4.5)

In [ ]:
np.mean(arr2d, axis=0) # mean based on the rows, so we get the mean for each column

array([5.25, 2.25, 5.5 , 5.25, 4.25])

In [41]:
arrb = arr <2
arrb

array([ True,  True, False, False])

In [42]:
arrb.dtype

dtype('bool')

In [43]:
arrb.all()

np.False_

In [44]:
arrb.any()

np.True_

In [45]:
arr1d = np.array([2,2,2,2])
arr1d

array([2, 2, 2, 2])

In [49]:
arr2d = np.arange(8).reshape(2,4)
arr2d

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [50]:
arr1d + arr2d

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [51]:
arr3d = np.arange(8).reshape(2,2,2)
arr3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [52]:
p1,p2 = arr3d

In [53]:
print(p1)

[[0 1]
 [2 3]]


In [56]:
v0, v1 = p1
print(v0)

[0 1]
