## Create arrays

In [17]:
arr1d = np.arange(11,51,3)
arr1d

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [22]:
arr1d.dtype

dtype('int64')

In [23]:
arr1d.shape

(14,)

In [24]:
arr1d.ndim

1

In [26]:
arr2d_b = np.zeros((5,3), dtype=bool)
arr2d_b

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [29]:
alph = np.array(list('abcdefghijklmnopqrstuvwxyz '))
arr2d_alph = np.array(alph).reshape(9,3)
arr2d_alph

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i'],
       ['j', 'k', 'l'],
       ['m', 'n', 'o'],
       ['p', 'q', 'r'],
       ['s', 't', 'u'],
       ['v', 'w', 'x'],
       ['y', 'z', ' ']], dtype='<U1')

In [31]:
arr_c = np.array([ 5,  9, 16, 12,  3, 14, 11, 13]).reshape((2,2,2), order='C')
print(arr_c)

[[[ 5  9]
  [16 12]]

 [[ 3 14]
  [11 13]]]


In [32]:
arr_f = np.array([ 5,  9, 16, 12,  3, 14, 11, 13]).reshape((2,2,2), order='F')
print(arr_f)

[[[ 5  3]
  [16 11]]

 [[ 9 14]
  [12 13]]]


## Array indices

In [34]:
arr2d = np.array(list("abcdefghi")).reshape(3,3)
arr2d

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [40]:
print(arr2d[1,1])

e


In [41]:
print(arr2d[2,0])

g


In [42]:
print(arr2d[1,1:])

['e' 'f']


In [44]:
print(arr2d[::-1,1])

['h' 'e' 'b']


In [45]:
print(arr2d[2,1:])

['h' 'i']


In [46]:
print(arr2d[[1,0,1,2], [0,1,2,1]])

['d' 'b' 'f' 'h']


In [49]:
arr3d = np.arange(3*3*3).reshape(3,3,3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [50]:
print(arr3d[2, 0:2, 1:3])

[[19 20]
 [22 23]]


In [51]:
print(arr3d[1, :, [0,2]])

[[ 9 12 15]
 [11 14 17]]


In [53]:
print(arr3d[[0, 2, 1], :, :])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [54]:
print(arr3d[:, [2, 1, 0], :])

[[[ 6  7  8]
  [ 3  4  5]
  [ 0  1  2]]

 [[15 16 17]
  [12 13 14]
  [ 9 10 11]]

 [[24 25 26]
  [21 22 23]
  [18 19 20]]]


In [55]:
print(arr3d[0, [2, 1, 0], :])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [57]:
arr3d_copy = arr3d.copy()
arr3d_copy[arr3d_copy % 2 != 0] = -1
print(arr3d_copy)

[[[ 0 -1  2]
  [-1  4 -1]
  [ 6 -1  8]]

 [[-1 10 -1]
  [12 -1 14]
  [-1 16 -1]]

 [[18 -1 20]
  [-1 22 -1]
  [24 -1 26]]]


In [58]:
def identity_(n):
    matrix = np.zeros((n,n), dtype=int)

    for i in range(n):
        matrix[i, i] = 1
    return matrix

In [60]:
p1 = np.repeat([5, 3], 3)
p2 = np.tile([5, 7], 3)

arr = np.concatenate([p1, p2])
print(arr)

[5 5 5 3 3 3 5 7 5 7 5 7]


In [61]:
board = np.zeros((8, 8), dtype=int)
board[::2, ::2] = 1
board[1::2, 1::2] = 1

print(board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [62]:
def grid_x(n):
    grid=np.full((n,n), ".")

    index = np.arange(n)

    grid[index, index] = "#"
    grid[index, index[::-1]] = "#"

    return grid

## Array with summary

In [6]:
import numpy as np

In [11]:
arr2d = np.random.randint(0,100, size=(8,4))
print(arr2d)

[[47 45 11 42]
 [ 5 68 96 65]
 [23 44 90 56]
 [26 37 87  8]
 [23 32 82  9]
 [42 47  4 94]
 [59 79 12 93]
 [35 91 17 96]]


In [12]:
miminum = np.min(arr2d, axis =0)
maximum = np.max(arr2d, axis =0)
mean = np.mean(arr2d, axis =0)
median = np.median(arr2d, axis =0)
q1 = np.percentile(arr2d, 25, axis=0)
q3 = np.percentile(arr2d, 75, axis =0)

In [13]:
def summary(arr):
    mins = np.min(arr, axis=0)
    q1 = np.percentile(arr, 25, axis=0)
    median = np.median(arr, axis=0)
    mean = np.mean(arr, axis=0)
    q3 = np.percentile(arr, 75, axis=0)
    maxs = np.max(arr, axis=0)

    num_cols = arr.shape[1]

    labels = ["Min.   :", "1st Qu.:", "Median :", "Mean   :", "3rd Qu.:", "Max.   :"]
    stats_matrix = [mins, q1, median, mean, q3, maxs]

    header = ""
    for i in range(num_cols):
        header += f"{i:^20}"
    print(header)

    for row_idx, label in enumerate(labels):
        row_str = ""
        for col_idx in range(num_cols):
            val = stats_matrix[row_idx][col_idx]
            cell_content = f"{label}{val:<7.2f}"
            row_str += f"{cell_content:<20}"
        print(row_str)

In [14]:
summary(arr2d)

         0                   1                   2                   3          
Min.   :5.00        Min.   :32.00       Min.   :4.00        Min.   :8.00        
1st Qu.:23.00       1st Qu.:42.25       1st Qu.:11.75       1st Qu.:33.75       
Median :30.50       Median :46.00       Median :49.50       Median :60.50       
Mean   :32.50       Mean   :55.38       Mean   :49.88       Mean   :57.88       
3rd Qu.:43.25       3rd Qu.:70.75       3rd Qu.:87.75       3rd Qu.:93.25       
Max.   :59.00       Max.   :91.00       Max.   :96.00       Max.   :96.00       


In [15]:
def mat_mult(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    if cols_A != rows_B:
        raise ValueError(
            f"Incompatible dimensions for multiplication: {cols_A} columns in A "
            f"and {rows_B} rows in B."
        )

    result = np.zeros((rows_A, cols_B))
    
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i, j] += A[i, k] * B[k, j]